sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t streetlight-amd64 ci/

script:
  - ./run-amd64 ci/build.sh
  - ./run-amd64 ci/test.sh
  - ./run-amd64 ci/documentation.sh

