
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__TimerAdaptor_h__ADAPTOR_MARSHAL_H
#define __dbusxx__TimerAdaptor_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace ch {
namespace bbv {

class timer_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    timer_adaptor()
    : ::DBus::InterfaceAdaptor("ch.bbv.timer")
    {
        register_method(timer_adaptor, timeout, _timeout_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument timeout_args[] = 
        {
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod timer_adaptor_methods[] = 
        {
            { "timeout", timeout_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod timer_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty timer_adaptor_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface timer_adaptor_interface = 
        {
            "ch.bbv.timer",
            timer_adaptor_methods,
            timer_adaptor_signals,
            timer_adaptor_properties
        };
        return &timer_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual void timeout() = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _timeout_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        timeout();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};

} } 
#endif //__dbusxx__TimerAdaptor_h__ADAPTOR_MARSHAL_H
