
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__source_StreetlightProxy_h__PROXY_MARSHAL_H
#define __dbusxx__source_StreetlightProxy_h__PROXY_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace ch {
namespace bbv {
namespace StreetLight {

class Brightness_proxy
: public ::DBus::InterfaceProxy
{
public:

    Brightness_proxy()
    : ::DBus::InterfaceProxy("ch.bbv.StreetLight.Brightness")
    {
    }

public:

    /* properties exported by this interface */
        const double value() {
            ::DBus::CallMessage call ;
             call.member("Get"); call.interface("org.freedesktop.DBus.Properties");
            ::DBus::MessageIter wi = call.writer(); 
            const std::string interface_name = "ch.bbv.StreetLight.Brightness";
            const std::string property_name  = "value";
            wi << interface_name;
            wi << property_name;
            ::DBus::Message ret = this->invoke_method (call);
            ::DBus::MessageIter ri = ret.reader ();
            ::DBus::Variant argout; 
            ri >> argout;
            return argout;
        };
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */

public:

    /* signal handlers for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
};

} } } 
namespace ch {
namespace bbv {
namespace StreetLight {

class Lamp_proxy
: public ::DBus::InterfaceProxy
{
public:

    Lamp_proxy()
    : ::DBus::InterfaceProxy("ch.bbv.StreetLight.Lamp")
    {
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    void set(const double& value)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << value;
        call.member("set");
        ::DBus::Message ret = invoke_method (call);
    }


public:

    /* signal handlers for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
};

} } } 
#endif //__dbusxx__source_StreetlightProxy_h__PROXY_MARSHAL_H
